# -*- coding: utf-8 -*-
"""NumPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1riCYBEnnL_GnFxNfsAo2rUeO8_Oi_TbZ
"""

import numpy as np

a = np.array([23, 44, 67])
b = np.array([[22,33,44], [66,77,88]])

print(a)

print(b)

z = np.zeros((3,5))

print(z)

o = np.ones((3,5))

print(o)

r = np.random.rand(3,4)

print(r)

i = np.eye(5)

print(i)

print(a.shape)
print(b.shape)
print(a.ndim)
print(b.ndim)
print(a.size)
print(b.size)
print(a.dtype)
print(b.dtype)

